# WP Disease Tracker
# by Waren Gonzaga

# Love this project?

custom: ['https://buymeacoff.ee/warengonzaga','https://paypal.me/warengonzagaofficial']

# Your donation means a lot to me to continue the development of open source project like this.
